import type { GenerationTemplate } from "./lib/seed-expand";

/**
 * Hand-entered generation templates. Specs are shared across each year span.
 * Only cover years a model family plausibly existed — older decades use older family names.
 */
export const seedGenerations: GenerationTemplate[] = [
  // ─── Specialized Stumpjumper ─────────────────────────────────────────────
  {
    brandName: "Specialized",
    brandAliases: ["Specialized Bicycle Components", "SBC"],
    scraperKey: "specialized",
    model: "Stumpjumper",
    family: "Stumpjumper",
    yearStart: 1990,
    yearEnd: 1997,
    category: "Mountain",
    subcategory: "Trail",
    sourceUrl: "https://www.specialized.com/",
    confidence: 0.55,
    components: [
      { slot: "FRAME_MATERIAL", value: "Chromoly steel or aluminum (varies by trim)" },
      { slot: "FORK", value: "Rigid or early RockShox / Manitou suspension", detail: "Options by year/trim" },
      { slot: "FRONT_TRAVEL", value: "0–80 mm" },
      { slot: "SHIFTERS", value: "Shimano Deore / LX thumb or Rapidfire" },
      { slot: "REAR_DERAILLEUR", value: "Shimano Deore / LX" },
      { slot: "FRONT_DERAILLEUR", value: "Shimano Deore" },
      { slot: "CASSETTE", value: "7-speed freewheel / cassette, ~11-28t" },
      { slot: "CRANKSET", value: "Triple crankset (22/32/44 typical)" },
      { slot: "BOTTOM_BRACKET", value: "Square taper", standard: "BSA" },
      { slot: "BRAKES", value: "Cantilever or V-brake" },
      { slot: "WHEEL_SIZE", value: '26"' },
      { slot: "TIRES", value: "Specialized Ground Control / similar 26x2.0–2.2" },
    ],
  },
  {
    brandName: "Specialized",
    brandAliases: ["Specialized Bicycle Components", "SBC"],
    scraperKey: "specialized",
    model: "Stumpjumper FSR",
    family: "Stumpjumper",
    yearStart: 1998,
    yearEnd: 2004,
    category: "Mountain",
    subcategory: "Trail",
    sourceUrl: "https://www.specialized.com/",
    confidence: 0.6,
    components: [
      { slot: "FRAME_MATERIAL", value: "M4 aluminum (FSR full suspension)" },
      { slot: "FORK", value: "RockShox / Fox / Manitou, ~80–100mm" },
      { slot: "REAR_SHOCK", value: "Fox / Progressive / Specialized coil or air" },
      { slot: "FRONT_TRAVEL", value: "80–100 mm" },
      { slot: "REAR_TRAVEL", value: "80–100 mm" },
      { slot: "SHIFTERS", value: "Shimano Deore / LX / XT" },
      { slot: "REAR_DERAILLEUR", value: "Shimano Deore / LX / XT" },
      { slot: "CASSETTE", value: "8/9-speed, ~11-32t" },
      { slot: "CRANKSET", value: "Shimano Octalink / Hollowtech triple" },
      { slot: "BOTTOM_BRACKET", value: "Shimano Octalink or square taper", standard: "BSA" },
      { slot: "BRAKES", value: "V-brake or early hydraulic disc" },
      { slot: "WHEEL_SIZE", value: '26"' },
      { slot: "TIRES", value: "Specialized 26x2.0–2.2" },
    ],
  },
  {
    brandName: "Specialized",
    brandAliases: ["Specialized Bicycle Components", "SBC"],
    scraperKey: "specialized",
    model: "Stumpjumper",
    family: "Stumpjumper",
    yearStart: 2005,
    yearEnd: 2010,
    category: "Mountain",
    subcategory: "Trail",
    sourceUrl: null,
    confidence: 0.75,
    components: [
      {
        slot: "FRAME_MATERIAL",
        value: "M4 or M5 aluminum alloy (ORE)",
        detail: "Varies by trim",
      },
      {
        slot: "REAR_SHOCK",
        value: "Fox Float Septune (120mm) or Fox Float Triad (100mm)",
        detail: "FSR models",
      },
      {
        slot: "FORK",
        value: "Fox Talas RL/RLC (95–130mm), Fox F80RL (80mm), or Manitou Black Elite (100mm)",
        detail: "Options by trim",
      },
      { slot: "FRONT_TRAVEL", value: "80–130 mm", detail: "Depends on fork option" },
      { slot: "REAR_TRAVEL", value: "100–120 mm", detail: "FSR models" },
      { slot: "CRANKSET", value: "Custom Shimano Hollowtech / Octalink (22/32/44t)" },
      {
        slot: "BOTTOM_BRACKET",
        value: "Shimano ES-30 Octalink",
        standard: "Octalink spline",
      },
      { slot: "CASSETTE", value: "Shimano 9-speed 11-34t" },
      {
        slot: "SHIFTERS",
        value: "Shimano Deore LX, XT, or XTR",
        detail: "Mix depending on trim",
      },
      {
        slot: "REAR_DERAILLEUR",
        value: "Shimano Deore LX, XT, or XTR",
        detail: "Mix depending on trim",
      },
      { slot: "BRAKES", value: "Avid Juicy 7 hydraulic disc or Shimano XTR disc" },
      { slot: "RIMS", value: "Mavic X317 disc, 32-hole" },
      { slot: "WHEEL_SIZE", value: '26"' },
      { slot: "FRONT_HUB", value: "Specialized Stout Disc" },
      { slot: "REAR_HUB", value: "Shimano M-525 / Deore Disc" },
      {
        slot: "TIRES",
        value: "Specialized Resolution Pro or Adrenaline Pro, 26x2.00",
      },
    ],
  },
  {
    brandName: "Specialized",
    brandAliases: ["Specialized Bicycle Components", "SBC"],
    scraperKey: "specialized",
    model: "Stumpjumper FSR",
    family: "Stumpjumper",
    yearStart: 2011,
    yearEnd: 2015,
    category: "Mountain",
    subcategory: "Trail",
    sourceUrl: "https://www.specialized.com/",
    confidence: 0.65,
    components: [
      { slot: "FRAME_MATERIAL", value: "M5 aluminum or FACT carbon (trim dependent)" },
      { slot: "FORK", value: "Fox / RockShox, ~120–140mm" },
      { slot: "REAR_SHOCK", value: "Fox Float / Custom Specialized" },
      { slot: "FRONT_TRAVEL", value: "120–140 mm" },
      { slot: "REAR_TRAVEL", value: "120–140 mm" },
      { slot: "SHIFTERS", value: "Shimano Deore / SLX or SRAM X7/X9" },
      { slot: "REAR_DERAILLEUR", value: "Shimano / SRAM 10-speed" },
      { slot: "CASSETTE", value: "10-speed, ~11-36t" },
      { slot: "CRANKSET", value: "2x or 1x trail crankset" },
      { slot: "BOTTOM_BRACKET", value: "PF30 or BSA", standard: "Varies by year" },
      { slot: "BRAKES", value: "Shimano / Avid / SRAM hydraulic disc" },
      { slot: "WHEEL_SIZE", value: '26" or 29"', detail: "29er options expand mid-generation" },
      { slot: "TIRES", value: "Specialized Purgatory / Ground Control" },
    ],
  },
  {
    brandName: "Specialized",
    brandAliases: ["Specialized Bicycle Components", "SBC"],
    scraperKey: "specialized",
    model: "Stumpjumper",
    family: "Stumpjumper",
    yearStart: 2016,
    yearEnd: 2020,
    category: "Mountain",
    subcategory: "Trail",
    sourceUrl: "https://www.specialized.com/",
    confidence: 0.7,
    components: [
      { slot: "FRAME_MATERIAL", value: "FACT carbon or M5 aluminum" },
      { slot: "FORK", value: "Fox Float 34 / RockShox Pike, ~130–150mm" },
      { slot: "REAR_SHOCK", value: "Fox Float DPS / RockShox Deluxe" },
      { slot: "FRONT_TRAVEL", value: "130–150 mm" },
      { slot: "REAR_TRAVEL", value: "130–140 mm" },
      { slot: "SHIFTERS", value: "SRAM GX / NX Eagle or Shimano SLX" },
      { slot: "REAR_DERAILLEUR", value: "SRAM Eagle 12-speed or Shimano 11/12-speed" },
      { slot: "CASSETTE", value: "SRAM NX/GX 11-50t or Shimano 11-51t" },
      { slot: "CRANKSET", value: "SRAM / Shimano 1x, 30–32t" },
      { slot: "BOTTOM_BRACKET", value: "SRAM DUB or Shimano Threaded", standard: "BSA" },
      { slot: "BRAKES", value: "SRAM Guide / Code or Shimano XT/SLX" },
      { slot: "WHEEL_SIZE", value: '29" or 27.5"', detail: "Mullet options on later years" },
      { slot: "TIRES", value: "Specialized Butcher / Eliminator" },
      { slot: "AXLE", value: "Boost 148mm rear / 110mm front" },
    ],
  },
  {
    brandName: "Specialized",
    brandAliases: ["Specialized Bicycle Components", "SBC"],
    scraperKey: "specialized",
    model: "Stumpjumper Comp",
    family: "Stumpjumper",
    yearStart: 2021,
    yearEnd: 2026,
    category: "Mountain",
    subcategory: "Trail",
    sourceUrl: "https://www.specialized.com/",
    confidence: 0.85,
    components: [
      { slot: "FRAME_MATERIAL", value: "FACT 11m carbon" },
      { slot: "FORK", value: "Fox Float 34 Rhythm, 140mm" },
      { slot: "REAR_SHOCK", value: "Fox Float Performance" },
      { slot: "FRONT_TRAVEL", value: "140 mm" },
      { slot: "REAR_TRAVEL", value: "130 mm" },
      { slot: "SHIFTERS", value: "SRAM GX Eagle" },
      { slot: "REAR_DERAILLEUR", value: "SRAM GX Eagle, 12-speed" },
      { slot: "CASSETTE", value: "SRAM NX Eagle PG-1230, 11-50t" },
      { slot: "CRANKSET", value: "SRAM NX Eagle, 30t" },
      { slot: "CHAIN", value: "SRAM NX Eagle" },
      { slot: "BOTTOM_BRACKET", value: "SRAM DUB", standard: "BSA threaded" },
      { slot: "BRAKES", value: "SRAM Code R, 4-piston" },
      { slot: "DISC_ROTORS", value: "200/180mm" },
      { slot: "WHEEL_SIZE", value: '29"' },
      { slot: "TIRES", value: "Specialized Eliminator Grid Trail 2.3" },
      { slot: "DERAILLEUR_HANGER", value: "SRAM UDH", standard: "UDH" },
      { slot: "AXLE", value: "Boost 148mm rear / 110mm front" },
      { slot: "SADDLE", value: "Bridge Comp" },
      { slot: "HANDLEBAR", value: "Specialized Alloy Trail" },
    ],
  },

  // ─── Specialized Allez ───────────────────────────────────────────────────
  {
    brandName: "Specialized",
    brandAliases: ["Specialized Bicycle Components", "SBC"],
    scraperKey: "specialized",
    model: "Allez",
    family: "Allez",
    yearStart: 1990,
    yearEnd: 1999,
    category: "Road",
    sourceUrl: "https://www.specialized.com/",
    confidence: 0.55,
    components: [
      { slot: "FRAME_MATERIAL", value: "Aluminum road frame" },
      { slot: "FORK", value: "Chromoly or aluminum road fork" },
      { slot: "SHIFTERS", value: "Shimano 105 / Tiagra downtube or STI" },
      { slot: "REAR_DERAILLEUR", value: "Shimano 105 / Tiagra" },
      { slot: "FRONT_DERAILLEUR", value: "Shimano 105 / Tiagra" },
      { slot: "CASSETTE", value: "7/8-speed" },
      { slot: "CRANKSET", value: "Double crankset ~52/39" },
      { slot: "BOTTOM_BRACKET", value: "Square taper", standard: "BSA 68mm" },
      { slot: "BRAKES", value: "Dual-pivot caliper" },
      { slot: "WHEEL_SIZE", value: "700c" },
      { slot: "TIRES", value: "700x23–25" },
    ],
  },
  {
    brandName: "Specialized",
    brandAliases: ["Specialized Bicycle Components", "SBC"],
    scraperKey: "specialized",
    model: "Allez",
    family: "Allez",
    yearStart: 2000,
    yearEnd: 2011,
    category: "Road",
    sourceUrl: "https://www.specialized.com/",
    confidence: 0.6,
    components: [
      { slot: "FRAME_MATERIAL", value: "A1 / E5 aluminum" },
      { slot: "FORK", value: "Specialized carbon or alloy" },
      { slot: "SHIFTERS", value: "Shimano Sora / Tiagra / 105" },
      { slot: "REAR_DERAILLEUR", value: "Shimano Sora / Tiagra / 105" },
      { slot: "FRONT_DERAILLEUR", value: "Shimano Sora / Tiagra / 105" },
      { slot: "CASSETTE", value: "8/9/10-speed" },
      { slot: "CRANKSET", value: "Compact or standard double" },
      { slot: "BOTTOM_BRACKET", value: "Shimano threaded", standard: "BSA 68mm" },
      { slot: "BRAKES", value: "Shimano / Tektro caliper" },
      { slot: "WHEEL_SIZE", value: "700c" },
      { slot: "TIRES", value: "Specialized Espoir / Roubaix 700x23–28" },
    ],
  },
  {
    brandName: "Specialized",
    brandAliases: ["Specialized Bicycle Components", "SBC"],
    scraperKey: "specialized",
    model: "Allez Sport",
    family: "Allez",
    yearStart: 2012,
    yearEnd: 2026,
    category: "Road",
    sourceUrl: "https://www.specialized.com/",
    confidence: 0.8,
    components: [
      { slot: "FRAME_MATERIAL", value: "E5 Premium Aluminum" },
      { slot: "FORK", value: "Specialized FACT carbon" },
      { slot: "SHIFTERS", value: "Shimano Tiagra" },
      { slot: "REAR_DERAILLEUR", value: "Shimano Tiagra" },
      { slot: "FRONT_DERAILLEUR", value: "Shimano Tiagra" },
      { slot: "CASSETTE", value: "Shimano Tiagra, 12-28t" },
      { slot: "CRANKSET", value: "Shimano Tiagra, 50/34t" },
      { slot: "BOTTOM_BRACKET", value: "Shimano threaded", standard: "BSA 68mm" },
      { slot: "BRAKES", value: "Tektro rim brakes" },
      { slot: "WHEEL_SIZE", value: "700c" },
      { slot: "TIRES", value: "Specialized Espoir Sport 700x28" },
      { slot: "DERAILLEUR_HANGER", value: "Specialized replaceable" },
      { slot: "SADDLE", value: "Body Geometry Bridge" },
    ],
  },

  // ─── Trek (older hardtails → Marlin) ─────────────────────────────────────
  {
    brandName: "Trek",
    brandAliases: ["Trek Bicycle"],
    scraperKey: "trek",
    model: "820",
    family: "820",
    yearStart: 1990,
    yearEnd: 1999,
    category: "Mountain",
    subcategory: "Hardtail",
    sourceUrl: "https://www.trekbikes.com/",
    confidence: 0.55,
    components: [
      { slot: "FRAME_MATERIAL", value: "Chromoly or Alpha aluminum" },
      { slot: "FORK", value: "Rigid or early suspension" },
      { slot: "SHIFTERS", value: "Shimano Tourney / Altus" },
      { slot: "REAR_DERAILLEUR", value: "Shimano Tourney / Altus" },
      { slot: "CASSETTE", value: "7-speed freewheel" },
      { slot: "CRANKSET", value: "Triple crankset" },
      { slot: "BOTTOM_BRACKET", value: "Square taper", standard: "BSA" },
      { slot: "BRAKES", value: "Cantilever or V-brake" },
      { slot: "WHEEL_SIZE", value: '26"' },
      { slot: "TIRES", value: "Trek / Bontrager 26x1.95–2.1" },
    ],
  },
  {
    brandName: "Trek",
    brandAliases: ["Trek Bicycle"],
    scraperKey: "trek",
    model: "4300",
    family: "4300",
    yearStart: 2000,
    yearEnd: 2014,
    category: "Mountain",
    subcategory: "Hardtail",
    sourceUrl: "https://www.trekbikes.com/",
    confidence: 0.6,
    components: [
      { slot: "FRAME_MATERIAL", value: "Alpha aluminum" },
      { slot: "FORK", value: "SR Suntour / RockShox, ~80–100mm" },
      { slot: "FRONT_TRAVEL", value: "80–100 mm" },
      { slot: "SHIFTERS", value: "Shimano Altus / Acera / Deore" },
      { slot: "REAR_DERAILLEUR", value: "Shimano Altus / Acera / Deore" },
      { slot: "CASSETTE", value: "8/9-speed" },
      { slot: "CRANKSET", value: "Shimano square taper or Octalink triple" },
      { slot: "BOTTOM_BRACKET", value: "Cartridge", standard: "BSA" },
      { slot: "BRAKES", value: "V-brake or mechanical/hydraulic disc" },
      { slot: "WHEEL_SIZE", value: '26"' },
      { slot: "TIRES", value: "Bontrager 26x2.0–2.2" },
    ],
  },
  {
    brandName: "Trek",
    brandAliases: ["Trek Bicycle"],
    scraperKey: "trek",
    model: "Marlin 7",
    family: "Marlin",
    yearStart: 2015,
    yearEnd: 2026,
    category: "Mountain",
    subcategory: "Trail",
    sourceUrl: "https://www.trekbikes.com/",
    confidence: 0.85,
    components: [
      { slot: "FRAME_MATERIAL", value: "Alpha Gold Aluminum" },
      { slot: "FORK", value: "RockShox Judy Silver TK, 100mm" },
      { slot: "FRONT_TRAVEL", value: "100 mm" },
      { slot: "SHIFTERS", value: "Shimano Deore M4100" },
      { slot: "REAR_DERAILLEUR", value: "Shimano Deore M5120" },
      { slot: "CASSETTE", value: "Shimano Deore M4100, 11-46, 10-speed" },
      { slot: "CRANKSET", value: "Shimano MT511, 30t" },
      { slot: "BOTTOM_BRACKET", value: "Shimano BB52", standard: "BSA threaded" },
      { slot: "BRAKES", value: "Shimano MT200 hydraulic disc" },
      { slot: "DISC_ROTORS", value: "Shimano RT26 180/160mm" },
      { slot: "WHEEL_SIZE", value: '29"' },
      { slot: "TIRES", value: "Bontrager XR3 Comp 29x2.20" },
      { slot: "DERAILLEUR_HANGER", value: "Trek/Bontrager" },
      { slot: "AXLE", value: "Boost 148mm" },
      { slot: "SADDLE", value: "Bontrager Arvada" },
    ],
  },

  // ─── Schwinn High Timber (modern only) ───────────────────────────────────
  {
    brandName: "Schwinn",
    brandAliases: ["Schwinn Bicycle"],
    scraperKey: "schwinn",
    model: "High Timber",
    family: "High Timber",
    yearStart: 2018,
    yearEnd: 2026,
    category: "Mountain",
    sourceUrl: "https://www.schwinnbikes.com/",
    confidence: 0.75,
    components: [
      { slot: "FRAME_MATERIAL", value: "Aluminum" },
      { slot: "FORK", value: "SR Suntour XCT, 80mm" },
      { slot: "FRONT_TRAVEL", value: "80 mm" },
      { slot: "SHIFTERS", value: "Shimano Tourney" },
      { slot: "REAR_DERAILLEUR", value: "Shimano Tourney" },
      { slot: "CASSETTE", value: "7-speed freewheel" },
      { slot: "BRAKES", value: "Mechanical disc" },
      { slot: "WHEEL_SIZE", value: '27.5"' },
      { slot: "TIRES", value: "Schwinn MTB 27.5x2.1" },
      { slot: "BOTTOM_BRACKET", value: "Square taper", standard: "BSA" },
    ],
  },
  {
    brandName: "Schwinn",
    brandAliases: ["Schwinn Bicycle"],
    scraperKey: "schwinn",
    model: "Moab",
    family: "Moab",
    yearStart: 1995,
    yearEnd: 2017,
    category: "Mountain",
    sourceUrl: "https://www.schwinnbikes.com/",
    confidence: 0.55,
    components: [
      { slot: "FRAME_MATERIAL", value: "Chromoly or aluminum" },
      { slot: "FORK", value: "Rigid or SR Suntour / RST, ~50–80mm" },
      { slot: "SHIFTERS", value: "Shimano Tourney / Altus" },
      { slot: "REAR_DERAILLEUR", value: "Shimano Tourney / Altus" },
      { slot: "CASSETTE", value: "7-speed freewheel" },
      { slot: "CRANKSET", value: "Triple crankset" },
      { slot: "BOTTOM_BRACKET", value: "Square taper", standard: "BSA" },
      { slot: "BRAKES", value: "V-brake or mechanical disc" },
      { slot: "WHEEL_SIZE", value: '26"' },
      { slot: "TIRES", value: "Schwinn MTB 26x2.0" },
    ],
  },

  // ─── Giant Escape + Trance (+ older ATX) ─────────────────────────────────
  {
    brandName: "Giant",
    brandAliases: ["Giant Bicycles", "Giant Manufacturing"],
    scraperKey: "giant",
    model: "ATX",
    family: "ATX",
    yearStart: 1990,
    yearEnd: 2009,
    category: "Mountain",
    subcategory: "Hardtail",
    sourceUrl: "https://www.giant-bicycles.com/",
    confidence: 0.55,
    components: [
      { slot: "FRAME_MATERIAL", value: "ALUXX / chromoly aluminum or steel" },
      { slot: "FORK", value: "Rigid or SR Suntour, ~50–80mm" },
      { slot: "SHIFTERS", value: "Shimano Tourney / Altus / Acera" },
      { slot: "REAR_DERAILLEUR", value: "Shimano Tourney / Altus" },
      { slot: "CASSETTE", value: "7/8-speed" },
      { slot: "CRANKSET", value: "Triple crankset" },
      { slot: "BOTTOM_BRACKET", value: "Cartridge", standard: "BSA" },
      { slot: "BRAKES", value: "V-brake" },
      { slot: "WHEEL_SIZE", value: '26"' },
      { slot: "TIRES", value: "Giant 26x1.95–2.1" },
    ],
  },
  {
    brandName: "Giant",
    brandAliases: ["Giant Bicycles", "Giant Manufacturing"],
    scraperKey: "giant",
    model: "Escape 3",
    family: "Escape",
    yearStart: 2010,
    yearEnd: 2026,
    category: "Hybrid",
    sourceUrl: "https://www.giant-bicycles.com/",
    confidence: 0.8,
    components: [
      { slot: "FRAME_MATERIAL", value: "ALUXX aluminum" },
      { slot: "FORK", value: "High-tensile steel" },
      { slot: "SHIFTERS", value: "Shimano Altus" },
      { slot: "REAR_DERAILLEUR", value: "Shimano Tourney" },
      { slot: "CASSETTE", value: "Shimano HG200, 12-32, 7-speed" },
      { slot: "BRAKES", value: "Tektro linear-pull" },
      { slot: "WHEEL_SIZE", value: "700c" },
      { slot: "TIRES", value: "Giant S-X3 700x38c" },
      { slot: "BOTTOM_BRACKET", value: "Cartridge", standard: "BSA" },
    ],
  },
  {
    brandName: "Giant",
    brandAliases: ["Giant Bicycles", "Giant Manufacturing"],
    scraperKey: "giant",
    model: "Trance",
    family: "Trance",
    yearStart: 2005,
    yearEnd: 2015,
    category: "Mountain",
    subcategory: "Trail",
    sourceUrl: "https://www.giant-bicycles.com/",
    confidence: 0.6,
    components: [
      { slot: "FRAME_MATERIAL", value: "ALUXX aluminum" },
      { slot: "FORK", value: "Fox / RockShox / Giant, ~120–140mm" },
      { slot: "REAR_SHOCK", value: "Fox Float / RockShox Monarch" },
      { slot: "FRONT_TRAVEL", value: "120–140 mm" },
      { slot: "REAR_TRAVEL", value: "120–140 mm" },
      { slot: "SHIFTERS", value: "Shimano Deore / SLX or SRAM X7" },
      { slot: "REAR_DERAILLEUR", value: "Shimano / SRAM 9/10-speed" },
      { slot: "CASSETTE", value: "9/10-speed" },
      { slot: "CRANKSET", value: "2x or triple trail crankset" },
      { slot: "BOTTOM_BRACKET", value: "Shimano press-fit or BSA", standard: "Varies" },
      { slot: "BRAKES", value: "Shimano / Avid hydraulic disc" },
      { slot: "WHEEL_SIZE", value: '26" or 27.5"' },
      { slot: "TIRES", value: "Schwalbe / Maxxis trail 2.2–2.4" },
    ],
  },
  {
    brandName: "Giant",
    brandAliases: ["Giant Bicycles", "Giant Manufacturing"],
    scraperKey: "giant",
    model: "Trance X 2",
    family: "Trance",
    yearStart: 2016,
    yearEnd: 2026,
    category: "Mountain",
    subcategory: "Trail",
    sourceUrl: "https://www.giant-bicycles.com/",
    confidence: 0.75,
    components: [
      { slot: "FRAME_MATERIAL", value: "ALUXX aluminum" },
      { slot: "FORK", value: "Giant Crest 34 RCL, 140mm" },
      { slot: "REAR_SHOCK", value: "Fox Float DPS Performance" },
      { slot: "FRONT_TRAVEL", value: "140 mm" },
      { slot: "REAR_TRAVEL", value: "135 mm" },
      { slot: "SHIFTERS", value: "Shimano Deore M6100" },
      { slot: "REAR_DERAILLEUR", value: "Shimano Deore M6100, 12-speed" },
      { slot: "CASSETTE", value: "Shimano Deore M6100, 10-51t" },
      { slot: "CRANKSET", value: "Praxis Cadet M24, 30t" },
      { slot: "CHAIN", value: "KMC X12" },
      { slot: "BOTTOM_BRACKET", value: "Praxis", standard: "BSA threaded" },
      { slot: "BRAKES", value: "Shimano BR-MT420, 4-piston" },
      { slot: "DISC_ROTORS", value: "180/180mm" },
      { slot: "WHEEL_SIZE", value: '29"' },
      { slot: "TIRES", value: "Maxxis Minion DHF / Dissector 29x2.5/2.4" },
      { slot: "DERAILLEUR_HANGER", value: "Giant replaceable" },
      { slot: "AXLE", value: "Boost 148mm rear / 110mm front" },
      { slot: "SADDLE", value: "Giant Romero" },
      { slot: "SEATPOST", value: "Giant Contact Switch dropper" },
    ],
  },

  // ─── Canyon (Nerve/Grand Canyon early → Spectral) ────────────────────────
  {
    brandName: "Canyon",
    brandAliases: ["Canyon Bicycles"],
    scraperKey: "canyon",
    model: "Grand Canyon",
    family: "Grand Canyon",
    yearStart: 2002,
    yearEnd: 2014,
    category: "Mountain",
    subcategory: "Hardtail",
    sourceUrl: "https://www.canyon.com/",
    confidence: 0.55,
    components: [
      { slot: "FRAME_MATERIAL", value: "Aluminum hardtail" },
      { slot: "FORK", value: "RockShox / Fox / SR Suntour, ~80–100mm" },
      { slot: "FRONT_TRAVEL", value: "80–100 mm" },
      { slot: "SHIFTERS", value: "Shimano Deore / SLX" },
      { slot: "REAR_DERAILLEUR", value: "Shimano Deore / SLX" },
      { slot: "CASSETTE", value: "9/10-speed" },
      { slot: "CRANKSET", value: "Shimano 2x or triple" },
      { slot: "BOTTOM_BRACKET", value: "Shimano BSA", standard: "BSA" },
      { slot: "BRAKES", value: "Shimano / Magura hydraulic disc" },
      { slot: "WHEEL_SIZE", value: '26" or 29"' },
      { slot: "TIRES", value: "Continental / Schwalbe XC-trail" },
    ],
  },
  {
    brandName: "Canyon",
    brandAliases: ["Canyon Bicycles"],
    scraperKey: "canyon",
    model: "Nerve",
    family: "Nerve",
    yearStart: 2008,
    yearEnd: 2015,
    category: "Mountain",
    subcategory: "Trail",
    sourceUrl: "https://www.canyon.com/",
    confidence: 0.6,
    components: [
      { slot: "FRAME_MATERIAL", value: "Aluminum or carbon full suspension" },
      { slot: "FORK", value: "Fox / RockShox, ~120–140mm" },
      { slot: "REAR_SHOCK", value: "Fox Float / RockShox Monarch" },
      { slot: "FRONT_TRAVEL", value: "120–140 mm" },
      { slot: "REAR_TRAVEL", value: "120–140 mm" },
      { slot: "SHIFTERS", value: "Shimano XT / SLX or SRAM X9" },
      { slot: "REAR_DERAILLEUR", value: "Shimano / SRAM 10-speed" },
      { slot: "CASSETTE", value: "10-speed" },
      { slot: "CRANKSET", value: "2x trail crankset" },
      { slot: "BOTTOM_BRACKET", value: "PressFit or BSA", standard: "Varies" },
      { slot: "BRAKES", value: "Shimano XT / Formula hydraulic disc" },
      { slot: "WHEEL_SIZE", value: '26" or 27.5"' },
      { slot: "TIRES", value: "Continental Trail King / Mountain King" },
    ],
  },
  {
    brandName: "Canyon",
    brandAliases: ["Canyon Bicycles"],
    scraperKey: "canyon",
    model: "Spectral 125 CF 7",
    family: "Spectral",
    yearStart: 2016,
    yearEnd: 2026,
    category: "Mountain",
    subcategory: "Trail",
    sourceUrl: "https://www.canyon.com/",
    confidence: 0.75,
    components: [
      { slot: "FRAME_MATERIAL", value: "Carbon (CF)" },
      { slot: "FORK", value: "Fox 36 Float Performance Elite GRIP2, 150mm" },
      { slot: "REAR_SHOCK", value: "Fox Float X Performance Elite" },
      { slot: "FRONT_TRAVEL", value: "150 mm" },
      { slot: "REAR_TRAVEL", value: "125 mm" },
      { slot: "SHIFTERS", value: "SRAM GX Eagle AXS" },
      { slot: "REAR_DERAILLEUR", value: "SRAM GX Eagle AXS, 12-speed" },
      { slot: "CASSETTE", value: "SRAM XG-1275 Eagle, 10-52t" },
      { slot: "CRANKSET", value: "SRAM GX Eagle, 32t" },
      { slot: "CHAIN", value: "SRAM GX Eagle" },
      { slot: "BOTTOM_BRACKET", value: "SRAM DUB", standard: "BSA threaded" },
      { slot: "BRAKES", value: "SRAM Code RSC, 4-piston" },
      { slot: "DISC_ROTORS", value: "200/180mm" },
      { slot: "WHEEL_SIZE", value: '29"' },
      { slot: "TIRES", value: "Maxxis Minion DHF / DHR II 29x2.5/2.4" },
      { slot: "DERAILLEUR_HANGER", value: "SRAM UDH", standard: "UDH" },
      { slot: "AXLE", value: "Boost 148mm rear / 110mm front" },
      { slot: "SADDLE", value: "Ergon SM10" },
      { slot: "SEATPOST", value: "Canyon Iridium dropper" },
    ],
  },

  // ─── Santa Cruz (Heckler/Bullit → Hightower) ─────────────────────────────
  {
    brandName: "Santa Cruz",
    brandAliases: ["Santa Cruz Bicycles", "SCB"],
    scraperKey: "santa-cruz",
    model: "Heckler",
    family: "Heckler",
    yearStart: 1996,
    yearEnd: 2009,
    category: "Mountain",
    subcategory: "All-mountain",
    sourceUrl: "https://www.santacruzbicycles.com/",
    confidence: 0.55,
    components: [
      { slot: "FRAME_MATERIAL", value: "Aluminum VPP full suspension" },
      { slot: "FORK", value: "Fox / Marzocchi / RockShox, ~100–150mm" },
      { slot: "REAR_SHOCK", value: "Fox / Progressive / Manitou" },
      { slot: "FRONT_TRAVEL", value: "100–150 mm" },
      { slot: "REAR_TRAVEL", value: "100–150 mm" },
      { slot: "SHIFTERS", value: "Shimano XT / XTR or SRAM X.0" },
      { slot: "REAR_DERAILLEUR", value: "Shimano / SRAM 8/9-speed" },
      { slot: "CASSETTE", value: "8/9-speed" },
      { slot: "CRANKSET", value: "Race Face / Shimano triple or 2x" },
      { slot: "BOTTOM_BRACKET", value: "Square taper or external", standard: "BSA" },
      { slot: "BRAKES", value: "Avid / Hayes / Shimano disc" },
      { slot: "WHEEL_SIZE", value: '26"' },
      { slot: "TIRES", value: "Maxxis / WTB 26x2.1–2.5" },
    ],
  },
  {
    brandName: "Santa Cruz",
    brandAliases: ["Santa Cruz Bicycles", "SCB"],
    scraperKey: "santa-cruz",
    model: "Bronson",
    family: "Bronson",
    yearStart: 2013,
    yearEnd: 2017,
    category: "Mountain",
    subcategory: "Enduro",
    sourceUrl: "https://www.santacruzbicycles.com/",
    confidence: 0.65,
    components: [
      { slot: "FRAME_MATERIAL", value: "Carbon or aluminum VPP" },
      { slot: "FORK", value: "Fox 36 / RockShox Pike, ~150–160mm" },
      { slot: "REAR_SHOCK", value: "Fox Float X / RockShox Monarch Plus" },
      { slot: "FRONT_TRAVEL", value: "150–160 mm" },
      { slot: "REAR_TRAVEL", value: "150 mm" },
      { slot: "SHIFTERS", value: "SRAM X01 / GX or Shimano XT" },
      { slot: "REAR_DERAILLEUR", value: "SRAM / Shimano 11-speed" },
      { slot: "CASSETTE", value: "11-speed" },
      { slot: "CRANKSET", value: "SRAM / Race Face 1x, 30–32t" },
      { slot: "BOTTOM_BRACKET", value: "SRAM GXP or PF30", standard: "Varies" },
      { slot: "BRAKES", value: "SRAM Guide / Shimano XT" },
      { slot: "WHEEL_SIZE", value: '27.5"' },
      { slot: "TIRES", value: "Maxxis Minion DHF / DHR II" },
      { slot: "AXLE", value: "142x12 or Boost depending on year" },
    ],
  },
  {
    brandName: "Santa Cruz",
    brandAliases: ["Santa Cruz Bicycles", "SCB"],
    scraperKey: "santa-cruz",
    model: "Hightower C S",
    family: "Hightower",
    yearStart: 2016,
    yearEnd: 2026,
    category: "Mountain",
    subcategory: "Trail",
    sourceUrl: "https://www.santacruzbicycles.com/",
    confidence: 0.75,
    components: [
      { slot: "FRAME_MATERIAL", value: "Carbon C" },
      { slot: "FORK", value: "RockShox Pike Select+, 150mm" },
      { slot: "REAR_SHOCK", value: "RockShox Super Deluxe Select+" },
      { slot: "FRONT_TRAVEL", value: "150 mm" },
      { slot: "REAR_TRAVEL", value: "145 mm" },
      { slot: "SHIFTERS", value: "SRAM GX Eagle" },
      { slot: "REAR_DERAILLEUR", value: "SRAM GX Eagle, 12-speed" },
      { slot: "CASSETTE", value: "SRAM XG-1275 Eagle, 10-52t" },
      { slot: "CRANKSET", value: "SRAM GX Eagle, 32t" },
      { slot: "CHAIN", value: "SRAM GX Eagle" },
      { slot: "BOTTOM_BRACKET", value: "SRAM DUB", standard: "BSA threaded" },
      { slot: "BRAKES", value: "SRAM Code R, 4-piston" },
      { slot: "DISC_ROTORS", value: "180/180mm" },
      { slot: "WHEEL_SIZE", value: '29"' },
      { slot: "TIRES", value: "Maxxis Minion DHF / Dissector 29x2.5/2.4" },
      { slot: "DERAILLEUR_HANGER", value: "SRAM UDH", standard: "UDH" },
      { slot: "AXLE", value: "Boost 148mm rear / 110mm front" },
      { slot: "SADDLE", value: "WTB Silverado" },
      { slot: "SEATPOST", value: "OneUp dropper" },
    ],
  },

  // ─── Scott Spark ─────────────────────────────────────────────────────────
  {
    brandName: "Scott",
    brandAliases: ["Scott Sports", "SCOTT"],
    scraperKey: "scott",
    model: "Spark",
    family: "Spark",
    yearStart: 2003,
    yearEnd: 2011,
    category: "Mountain",
    subcategory: "Cross-country",
    sourceUrl: "https://www.scott-sports.com/",
    confidence: 0.55,
    components: [
      { slot: "FRAME_MATERIAL", value: "Aluminum or carbon XC full suspension" },
      { slot: "FORK", value: "Fox / RockShox SID, ~80–100mm" },
      { slot: "REAR_SHOCK", value: "Fox Float / Nude shock system" },
      { slot: "FRONT_TRAVEL", value: "80–100 mm" },
      { slot: "REAR_TRAVEL", value: "80–100 mm" },
      { slot: "SHIFTERS", value: "Shimano XT / XTR or SRAM X.0" },
      { slot: "REAR_DERAILLEUR", value: "Shimano / SRAM 9/10-speed" },
      { slot: "CASSETTE", value: "9/10-speed" },
      { slot: "CRANKSET", value: "2x or triple XC crankset" },
      { slot: "BOTTOM_BRACKET", value: "Shimano / SRAM", standard: "BSA or PF" },
      { slot: "BRAKES", value: "Shimano XT / Avid Elixir" },
      { slot: "WHEEL_SIZE", value: '26"' },
      { slot: "TIRES", value: "Schwalbe Racing Ralph / Similar XC" },
    ],
  },
  {
    brandName: "Scott",
    brandAliases: ["Scott Sports", "SCOTT"],
    scraperKey: "scott",
    model: "Spark",
    family: "Spark",
    yearStart: 2012,
    yearEnd: 2019,
    category: "Mountain",
    subcategory: "Cross-country",
    sourceUrl: "https://www.scott-sports.com/",
    confidence: 0.65,
    components: [
      { slot: "FRAME_MATERIAL", value: "HMX / HMF carbon or alloy" },
      { slot: "FORK", value: "Fox 32 / RockShox Reba / SID, ~100–120mm" },
      { slot: "REAR_SHOCK", value: "Fox Nude / Float DPS" },
      { slot: "FRONT_TRAVEL", value: "100–120 mm" },
      { slot: "REAR_TRAVEL", value: "100–120 mm" },
      { slot: "SHIFTERS", value: "Shimano XT / SRAM GX" },
      { slot: "REAR_DERAILLEUR", value: "Shimano / SRAM 11-speed" },
      { slot: "CASSETTE", value: "11-speed" },
      { slot: "CRANKSET", value: "SRAM / Shimano 1x or 2x XC" },
      { slot: "BOTTOM_BRACKET", value: "PF92 or BSA", standard: "Varies" },
      { slot: "BRAKES", value: "Shimano XT / SRAM Level" },
      { slot: "WHEEL_SIZE", value: '29"' },
      { slot: "TIRES", value: "Schwalbe Racing Ralph / Rocket Ron" },
      { slot: "AXLE", value: "142x12 or Boost on later years" },
    ],
  },
  {
    brandName: "Scott",
    brandAliases: ["Scott Sports", "SCOTT"],
    scraperKey: "scott",
    model: "Spark 970",
    family: "Spark",
    yearStart: 2020,
    yearEnd: 2026,
    category: "Mountain",
    subcategory: "Cross-country",
    sourceUrl: "https://www.scott-sports.com/",
    confidence: 0.75,
    components: [
      { slot: "FRAME_MATERIAL", value: "Alloy" },
      { slot: "FORK", value: "RockShox Judy Silver TK Remote, 120mm" },
      { slot: "REAR_SHOCK", value: "RockShox Deluxe Select" },
      { slot: "FRONT_TRAVEL", value: "120 mm" },
      { slot: "REAR_TRAVEL", value: "120 mm" },
      { slot: "SHIFTERS", value: "Shimano Deore M6100" },
      { slot: "REAR_DERAILLEUR", value: "Shimano Deore M6100, 12-speed" },
      { slot: "CASSETTE", value: "Shimano Deore M6100, 10-51t" },
      { slot: "CRANKSET", value: "Shimano MT510, 32t" },
      { slot: "CHAIN", value: "Shimano CN-M6100" },
      { slot: "BOTTOM_BRACKET", value: "Shimano BB52", standard: "BSA threaded" },
      { slot: "BRAKES", value: "Shimano MT200 hydraulic disc" },
      { slot: "DISC_ROTORS", value: "180/160mm" },
      { slot: "WHEEL_SIZE", value: '29"' },
      { slot: "TIRES", value: "Schwalbe Wicked Will 29x2.4" },
      { slot: "DERAILLEUR_HANGER", value: "Scott replaceable" },
      { slot: "AXLE", value: "Boost 148mm rear / 110mm front" },
      { slot: "SADDLE", value: "Syncros Tofino 2.5" },
      { slot: "SEATPOST", value: "Syncros Duncan Dropper 2.0" },
    ],
  },

  // ─── Polygon (Xtrada → Siskiu) ───────────────────────────────────────────
  {
    brandName: "Polygon",
    brandAliases: ["Polygon Bikes", "United Bike"],
    scraperKey: "polygon",
    model: "Xtrada",
    family: "Xtrada",
    yearStart: 2010,
    yearEnd: 2017,
    category: "Mountain",
    subcategory: "Hardtail",
    sourceUrl: "https://www.polygonbikes.com/",
    confidence: 0.55,
    components: [
      { slot: "FRAME_MATERIAL", value: "ALX aluminum hardtail" },
      { slot: "FORK", value: "SR Suntour / RockShox, ~100mm" },
      { slot: "FRONT_TRAVEL", value: "100 mm" },
      { slot: "SHIFTERS", value: "Shimano Acera / Deore" },
      { slot: "REAR_DERAILLEUR", value: "Shimano Acera / Deore" },
      { slot: "CASSETTE", value: "9/10-speed" },
      { slot: "CRANKSET", value: "Shimano 2x or triple" },
      { slot: "BOTTOM_BRACKET", value: "Cartridge", standard: "BSA" },
      { slot: "BRAKES", value: "Shimano hydraulic or mechanical disc" },
      { slot: "WHEEL_SIZE", value: '27.5" or 29"' },
      { slot: "TIRES", value: "Schwalbe / Entity MTB" },
    ],
  },
  {
    brandName: "Polygon",
    brandAliases: ["Polygon Bikes", "United Bike"],
    scraperKey: "polygon",
    model: "Siskiu D7",
    family: "Siskiu",
    yearStart: 2016,
    yearEnd: 2020,
    category: "Mountain",
    subcategory: "Trail",
    sourceUrl: "https://www.polygonbikes.com/",
    confidence: 0.65,
    components: [
      { slot: "FRAME_MATERIAL", value: "ALX aluminum full suspension" },
      { slot: "FORK", value: "RockShox / Fox, ~140–150mm" },
      { slot: "REAR_SHOCK", value: "RockShox Deluxe / Fox Float" },
      { slot: "FRONT_TRAVEL", value: "140–150 mm" },
      { slot: "REAR_TRAVEL", value: "140–150 mm" },
      { slot: "SHIFTERS", value: "Shimano Deore / SLX" },
      { slot: "REAR_DERAILLEUR", value: "Shimano Deore / SLX 11/12-speed" },
      { slot: "CASSETTE", value: "11/12-speed" },
      { slot: "CRANKSET", value: "Shimano 1x, 30–32t" },
      { slot: "BOTTOM_BRACKET", value: "Shimano BSA", standard: "BSA threaded" },
      { slot: "BRAKES", value: "Shimano MT / Deore hydraulic disc" },
      { slot: "WHEEL_SIZE", value: '27.5" or 29"' },
      { slot: "TIRES", value: "Schwalbe Nobby Nic / Hans Dampf" },
      { slot: "AXLE", value: "Boost 148mm" },
    ],
  },
  {
    brandName: "Polygon",
    brandAliases: ["Polygon Bikes", "United Bike"],
    scraperKey: "polygon",
    model: "Siskiu T8",
    family: "Siskiu",
    yearStart: 2021,
    yearEnd: 2026,
    category: "Mountain",
    subcategory: "Trail",
    sourceUrl: "https://www.polygonbikes.com/",
    confidence: 0.75,
    components: [
      { slot: "FRAME_MATERIAL", value: "ALX aluminum" },
      { slot: "FORK", value: "Fox 36 Float Rhythm GRIP, 160mm" },
      { slot: "REAR_SHOCK", value: "Fox Float X Performance" },
      { slot: "FRONT_TRAVEL", value: "160 mm" },
      { slot: "REAR_TRAVEL", value: "150 mm" },
      { slot: "SHIFTERS", value: "Shimano SLX M7100" },
      { slot: "REAR_DERAILLEUR", value: "Shimano SLX M7100, 12-speed" },
      { slot: "CASSETTE", value: "Shimano SLX M7100, 10-51t" },
      { slot: "CRANKSET", value: "Shimano SLX M7120, 32t" },
      { slot: "CHAIN", value: "Shimano CN-M7100" },
      { slot: "BOTTOM_BRACKET", value: "Shimano BB52", standard: "BSA threaded" },
      { slot: "BRAKES", value: "Shimano Deore M6120, 4-piston" },
      { slot: "DISC_ROTORS", value: "203/180mm" },
      { slot: "WHEEL_SIZE", value: '29"' },
      { slot: "TIRES", value: "Schwalbe Nobby Nic / Hans Dampf 29x2.4" },
      { slot: "DERAILLEUR_HANGER", value: "Polygon replaceable" },
      { slot: "AXLE", value: "Boost 148mm rear / 110mm front" },
      { slot: "SADDLE", value: "Entity" },
      { slot: "SEATPOST", value: "Entity dropper" },
    ],
  },

  // ─── Cannondale ──────────────────────────────────────────────────────────
  {
    brandName: "Cannondale",
    brandAliases: ["Cannondale Bicycle"],
    scraperKey: "cannondale",
    model: "F-Series",
    family: "F-Series",
    yearStart: 1990,
    yearEnd: 2004,
    category: "Mountain",
    subcategory: "Hardtail",
    sourceUrl: "https://www.cannondale.com/",
    confidence: 0.55,
    components: [
      { slot: "FRAME_MATERIAL", value: "CAAD aluminum hardtail" },
      { slot: "FORK", value: "HeadShok / rigid / early suspension" },
      { slot: "SHIFTERS", value: "Shimano Deore / LX" },
      { slot: "REAR_DERAILLEUR", value: "Shimano Deore / LX" },
      { slot: "CASSETTE", value: "7/8-speed" },
      { slot: "CRANKSET", value: "Triple crankset" },
      { slot: "BOTTOM_BRACKET", value: "Square taper", standard: "BSA" },
      { slot: "BRAKES", value: "Cantilever or V-brake" },
      { slot: "WHEEL_SIZE", value: '26"' },
      { slot: "TIRES", value: "Cannondale / IRC 26x1.95–2.1" },
    ],
  },
  {
    brandName: "Cannondale",
    brandAliases: ["Cannondale Bicycle"],
    scraperKey: "cannondale",
    model: "Trail",
    family: "Trail",
    yearStart: 2005,
    yearEnd: 2015,
    category: "Mountain",
    subcategory: "Hardtail",
    sourceUrl: "https://www.cannondale.com/",
    confidence: 0.6,
    components: [
      { slot: "FRAME_MATERIAL", value: "SmartFormed aluminum" },
      { slot: "FORK", value: "SR Suntour / RockShox, ~80–100mm" },
      { slot: "FRONT_TRAVEL", value: "80–100 mm" },
      { slot: "SHIFTERS", value: "Shimano Acera / Deore" },
      { slot: "REAR_DERAILLEUR", value: "Shimano Acera / Deore" },
      { slot: "CASSETTE", value: "8/9-speed" },
      { slot: "CRANKSET", value: "Shimano triple or 2x" },
      { slot: "BOTTOM_BRACKET", value: "Cartridge", standard: "BSA" },
      { slot: "BRAKES", value: "V-brake or hydraulic disc" },
      { slot: "WHEEL_SIZE", value: '26" or 29"' },
      { slot: "TIRES", value: "Schwalbe / Kenda MTB" },
    ],
  },
  {
    brandName: "Cannondale",
    brandAliases: ["Cannondale Bicycle"],
    scraperKey: "cannondale",
    model: "Habit 4",
    family: "Habit",
    yearStart: 2016,
    yearEnd: 2026,
    category: "Mountain",
    subcategory: "Trail",
    sourceUrl: "https://www.cannondale.com/",
    confidence: 0.7,
    components: [
      { slot: "FRAME_MATERIAL", value: "SmartFormed aluminum" },
      { slot: "FORK", value: "RockShox / Fox, ~130–140mm" },
      { slot: "REAR_SHOCK", value: "RockShox Deluxe / Fox Float" },
      { slot: "FRONT_TRAVEL", value: "130–140 mm" },
      { slot: "REAR_TRAVEL", value: "130 mm" },
      { slot: "SHIFTERS", value: "Shimano Deore / SRAM NX" },
      { slot: "REAR_DERAILLEUR", value: "Shimano / SRAM 12-speed" },
      { slot: "CASSETTE", value: "10-51t / 11-50t" },
      { slot: "CRANKSET", value: "1x, 30–32t" },
      { slot: "BOTTOM_BRACKET", value: "BSA threaded", standard: "BSA" },
      { slot: "BRAKES", value: "Shimano / SRAM hydraulic disc" },
      { slot: "WHEEL_SIZE", value: '29"' },
      { slot: "TIRES", value: "Maxxis / Schwalbe trail 2.4" },
      { slot: "AXLE", value: "Boost 148mm" },
    ],
  },

  // ─── Raleigh ─────────────────────────────────────────────────────────────
  {
    brandName: "Raleigh",
    brandAliases: ["Raleigh Bicycle", "Raleigh USA"],
    scraperKey: "raleigh",
    model: "Technium",
    family: "Technium",
    yearStart: 1990,
    yearEnd: 1999,
    category: "Mountain",
    subcategory: "Hardtail",
    sourceUrl: "https://www.raleighusa.com/",
    confidence: 0.5,
    components: [
      { slot: "FRAME_MATERIAL", value: "Chromoly or aluminum" },
      { slot: "FORK", value: "Rigid or early suspension" },
      { slot: "SHIFTERS", value: "Shimano Tourney / Altus" },
      { slot: "REAR_DERAILLEUR", value: "Shimano Tourney" },
      { slot: "CASSETTE", value: "7-speed freewheel" },
      { slot: "CRANKSET", value: "Triple crankset" },
      { slot: "BOTTOM_BRACKET", value: "Square taper", standard: "BSA" },
      { slot: "BRAKES", value: "Cantilever or V-brake" },
      { slot: "WHEEL_SIZE", value: '26"' },
      { slot: "TIRES", value: "Raleigh / generic MTB 26x1.95" },
    ],
  },
  {
    brandName: "Raleigh",
    brandAliases: ["Raleigh Bicycle", "Raleigh USA"],
    scraperKey: "raleigh",
    model: "Alysa",
    family: "Alysa",
    yearStart: 2000,
    yearEnd: 2015,
    category: "Hybrid",
    sourceUrl: "https://www.raleighusa.com/",
    confidence: 0.55,
    components: [
      { slot: "FRAME_MATERIAL", value: "Aluminum" },
      { slot: "FORK", value: "Steel or SR Suntour comfort" },
      { slot: "SHIFTERS", value: "Shimano Tourney / Altus" },
      { slot: "REAR_DERAILLEUR", value: "Shimano Tourney" },
      { slot: "CASSETTE", value: "7/8-speed" },
      { slot: "BRAKES", value: "V-brake" },
      { slot: "WHEEL_SIZE", value: "700c" },
      { slot: "TIRES", value: "700x35–38c" },
      { slot: "BOTTOM_BRACKET", value: "Cartridge", standard: "BSA" },
    ],
  },
  {
    brandName: "Raleigh",
    brandAliases: ["Raleigh Bicycle", "Raleigh USA"],
    scraperKey: "raleigh",
    model: "Tokul",
    family: "Tokul",
    yearStart: 2016,
    yearEnd: 2026,
    category: "Mountain",
    subcategory: "Hardtail",
    sourceUrl: "https://www.raleighusa.com/",
    confidence: 0.6,
    components: [
      { slot: "FRAME_MATERIAL", value: "Aluminum hardtail" },
      { slot: "FORK", value: "SR Suntour, ~100mm" },
      { slot: "FRONT_TRAVEL", value: "100 mm" },
      { slot: "SHIFTERS", value: "Shimano Altus / Acera" },
      { slot: "REAR_DERAILLEUR", value: "Shimano Altus / Acera" },
      { slot: "CASSETTE", value: "8/9-speed" },
      { slot: "BRAKES", value: "Mechanical or hydraulic disc" },
      { slot: "WHEEL_SIZE", value: '27.5" or 29"' },
      { slot: "TIRES", value: "Kenda MTB 2.1–2.25" },
      { slot: "BOTTOM_BRACKET", value: "Cartridge", standard: "BSA" },
    ],
  },

  // ─── GT ──────────────────────────────────────────────────────────────────
  {
    brandName: "GT",
    brandAliases: ["GT Bicycles"],
    scraperKey: "gt",
    model: "Timberline",
    family: "Timberline",
    yearStart: 1990,
    yearEnd: 2005,
    category: "Mountain",
    subcategory: "Hardtail",
    sourceUrl: "https://www.gtbicycles.com/",
    confidence: 0.55,
    components: [
      { slot: "FRAME_MATERIAL", value: "Chromoly or aluminum triple-triangle" },
      { slot: "FORK", value: "Rigid or RockShox / RST" },
      { slot: "SHIFTERS", value: "Shimano Deore / LX" },
      { slot: "REAR_DERAILLEUR", value: "Shimano Deore / LX" },
      { slot: "CASSETTE", value: "7/8-speed" },
      { slot: "CRANKSET", value: "Triple crankset" },
      { slot: "BOTTOM_BRACKET", value: "Square taper", standard: "BSA" },
      { slot: "BRAKES", value: "Cantilever or V-brake" },
      { slot: "WHEEL_SIZE", value: '26"' },
      { slot: "TIRES", value: "GT / IRC 26x2.0" },
    ],
  },
  {
    brandName: "GT",
    brandAliases: ["GT Bicycles"],
    scraperKey: "gt",
    model: "Aggressor",
    family: "Aggressor",
    yearStart: 2006,
    yearEnd: 2026,
    category: "Mountain",
    subcategory: "Hardtail",
    sourceUrl: "https://www.gtbicycles.com/",
    confidence: 0.65,
    components: [
      { slot: "FRAME_MATERIAL", value: "Aluminum" },
      { slot: "FORK", value: "SR Suntour / RockShox, ~80–100mm" },
      { slot: "FRONT_TRAVEL", value: "80–100 mm" },
      { slot: "SHIFTERS", value: "Shimano Tourney / Altus / Acera" },
      { slot: "REAR_DERAILLEUR", value: "Shimano Tourney / Altus" },
      { slot: "CASSETTE", value: "7/8/9-speed" },
      { slot: "BRAKES", value: "V-brake or mechanical disc" },
      { slot: "WHEEL_SIZE", value: '26", 27.5", or 29"' },
      { slot: "TIRES", value: "Kenda / WTB MTB" },
      { slot: "BOTTOM_BRACKET", value: "Cartridge", standard: "BSA" },
    ],
  },

  // ─── Fuji ────────────────────────────────────────────────────────────────
  {
    brandName: "Fuji",
    brandAliases: ["Fuji Bikes", "Fuji America"],
    scraperKey: "fuji",
    model: "Nevada",
    family: "Nevada",
    yearStart: 1990,
    yearEnd: 2009,
    category: "Mountain",
    subcategory: "Hardtail",
    sourceUrl: "https://www.fujibikes.com/",
    confidence: 0.55,
    components: [
      { slot: "FRAME_MATERIAL", value: "Chromoly or aluminum" },
      { slot: "FORK", value: "Rigid or SR Suntour" },
      { slot: "SHIFTERS", value: "Shimano Tourney / Altus" },
      { slot: "REAR_DERAILLEUR", value: "Shimano Tourney" },
      { slot: "CASSETTE", value: "7-speed freewheel" },
      { slot: "CRANKSET", value: "Triple crankset" },
      { slot: "BOTTOM_BRACKET", value: "Square taper", standard: "BSA" },
      { slot: "BRAKES", value: "V-brake" },
      { slot: "WHEEL_SIZE", value: '26"' },
      { slot: "TIRES", value: "Fuji / Kenda 26x1.95" },
    ],
  },
  {
    brandName: "Fuji",
    brandAliases: ["Fuji Bikes", "Fuji America"],
    scraperKey: "fuji",
    model: "Absolute",
    family: "Absolute",
    yearStart: 2010,
    yearEnd: 2026,
    category: "Hybrid",
    sourceUrl: "https://www.fujibikes.com/",
    confidence: 0.65,
    components: [
      { slot: "FRAME_MATERIAL", value: "A2-SL aluminum" },
      { slot: "FORK", value: "Fuji steel or carbon" },
      { slot: "SHIFTERS", value: "Shimano Altus / Acera" },
      { slot: "REAR_DERAILLEUR", value: "Shimano Altus / Acera" },
      { slot: "CASSETTE", value: "8/9-speed" },
      { slot: "BRAKES", value: "Tektro V-brake or disc" },
      { slot: "WHEEL_SIZE", value: "700c" },
      { slot: "TIRES", value: "700x35–40c" },
      { slot: "BOTTOM_BRACKET", value: "Cartridge", standard: "BSA" },
    ],
  },

  // ─── Bianchi ─────────────────────────────────────────────────────────────
  {
    brandName: "Bianchi",
    brandAliases: ["Bianchi Bicycles", "F.I.V. Edoardo Bianchi"],
    scraperKey: "bianchi",
    model: "Reparto Corse",
    family: "Reparto Corse",
    yearStart: 1990,
    yearEnd: 2004,
    category: "Road",
    sourceUrl: "https://www.bianchi.com/",
    confidence: 0.55,
    components: [
      { slot: "FRAME_MATERIAL", value: "Columbus steel or aluminum" },
      { slot: "FORK", value: "Steel or early carbon" },
      { slot: "SHIFTERS", value: "Shimano 105 / Ultegra or Campagnolo" },
      { slot: "REAR_DERAILLEUR", value: "Shimano / Campagnolo" },
      { slot: "FRONT_DERAILLEUR", value: "Shimano / Campagnolo" },
      { slot: "CASSETTE", value: "7/8/9-speed" },
      { slot: "CRANKSET", value: "Double crankset" },
      { slot: "BOTTOM_BRACKET", value: "Square taper or external", standard: "BSA 68mm" },
      { slot: "BRAKES", value: "Dual-pivot caliper" },
      { slot: "WHEEL_SIZE", value: "700c" },
      { slot: "TIRES", value: "700x23–25" },
    ],
  },
  {
    brandName: "Bianchi",
    brandAliases: ["Bianchi Bicycles", "F.I.V. Edoardo Bianchi"],
    scraperKey: "bianchi",
    model: "Via Nirone 7",
    family: "Via Nirone",
    yearStart: 2005,
    yearEnd: 2026,
    category: "Road",
    sourceUrl: "https://www.bianchi.com/",
    confidence: 0.7,
    components: [
      { slot: "FRAME_MATERIAL", value: "Aluminum with Kevlar / hydroformed aluminum" },
      { slot: "FORK", value: "Bianchi carbon or alloy" },
      { slot: "SHIFTERS", value: "Shimano Claris / Sora / Tiagra" },
      { slot: "REAR_DERAILLEUR", value: "Shimano Claris / Sora / Tiagra" },
      { slot: "FRONT_DERAILLEUR", value: "Shimano Claris / Sora / Tiagra" },
      { slot: "CASSETTE", value: "8/9/10-speed" },
      { slot: "CRANKSET", value: "Compact double" },
      { slot: "BOTTOM_BRACKET", value: "Shimano threaded", standard: "BSA 68mm" },
      { slot: "BRAKES", value: "Caliper or disc (later years)" },
      { slot: "WHEEL_SIZE", value: "700c" },
      { slot: "TIRES", value: "700x25–28" },
    ],
  },

  // ─── Peugeot ─────────────────────────────────────────────────────────────
  {
    brandName: "Peugeot",
    brandAliases: ["Cycles Peugeot"],
    scraperKey: "peugeot",
    model: "PZ10",
    family: "PZ",
    yearStart: 1990,
    yearEnd: 1999,
    category: "Road",
    sourceUrl: null,
    confidence: 0.5,
    components: [
      { slot: "FRAME_MATERIAL", value: "Carbolite / Reynolds steel" },
      { slot: "FORK", value: "Steel road fork" },
      { slot: "SHIFTERS", value: "Simplex / Shimano downtube or friction" },
      { slot: "REAR_DERAILLEUR", value: "Simplex / Shimano" },
      { slot: "CASSETTE", value: "5/6/7-speed freewheel" },
      { slot: "CRANKSET", value: "Stronglight / triple or double" },
      { slot: "BOTTOM_BRACKET", value: "Square taper", standard: "French or BSA" },
      { slot: "BRAKES", value: "Mafac / Weinmann centerpull or dual-pivot" },
      { slot: "WHEEL_SIZE", value: "700c" },
      { slot: "TIRES", value: "700x23–28" },
    ],
  },
  {
    brandName: "Peugeot",
    brandAliases: ["Cycles Peugeot"],
    scraperKey: "peugeot",
    model: "Hybrid / Mountain",
    family: "MTB",
    yearStart: 2000,
    yearEnd: 2026,
    category: "Hybrid",
    sourceUrl: null,
    confidence: 0.5,
    components: [
      { slot: "FRAME_MATERIAL", value: "Aluminum or steel" },
      { slot: "FORK", value: "Rigid or SR Suntour" },
      { slot: "SHIFTERS", value: "Shimano Tourney / Altus" },
      { slot: "REAR_DERAILLEUR", value: "Shimano Tourney" },
      { slot: "CASSETTE", value: "7/8-speed" },
      { slot: "BRAKES", value: "V-brake or disc" },
      { slot: "WHEEL_SIZE", value: '26" or 700c' },
      { slot: "TIRES", value: "Hybrid / MTB tread" },
      { slot: "BOTTOM_BRACKET", value: "Cartridge", standard: "BSA" },
    ],
  },

  // ─── Mongoose ────────────────────────────────────────────────────────────
  {
    brandName: "Mongoose",
    brandAliases: ["Mongoose Bicycles"],
    scraperKey: "mongoose",
    model: "Mountain Bike",
    family: "MTB",
    yearStart: 1990,
    yearEnd: 2009,
    category: "Mountain",
    subcategory: "Hardtail",
    sourceUrl: "https://www.mongoose.com/",
    confidence: 0.5,
    components: [
      { slot: "FRAME_MATERIAL", value: "Hi-Ten steel or aluminum" },
      { slot: "FORK", value: "Rigid or RST / SR Suntour" },
      { slot: "SHIFTERS", value: "Shimano Tourney" },
      { slot: "REAR_DERAILLEUR", value: "Shimano Tourney" },
      { slot: "CASSETTE", value: "7-speed freewheel" },
      { slot: "CRANKSET", value: "Triple crankset" },
      { slot: "BOTTOM_BRACKET", value: "Square taper", standard: "BSA" },
      { slot: "BRAKES", value: "V-brake" },
      { slot: "WHEEL_SIZE", value: '26"' },
      { slot: "TIRES", value: "Mongoose MTB 26x1.95–2.1" },
    ],
  },
  {
    brandName: "Mongoose",
    brandAliases: ["Mongoose Bicycles"],
    scraperKey: "mongoose",
    model: "Switchback",
    family: "Switchback",
    yearStart: 2010,
    yearEnd: 2026,
    category: "Mountain",
    subcategory: "Hardtail",
    sourceUrl: "https://www.mongoose.com/",
    confidence: 0.6,
    components: [
      { slot: "FRAME_MATERIAL", value: "Aluminum" },
      { slot: "FORK", value: "SR Suntour, ~80–100mm" },
      { slot: "FRONT_TRAVEL", value: "80–100 mm" },
      { slot: "SHIFTERS", value: "Shimano Tourney / Altus" },
      { slot: "REAR_DERAILLEUR", value: "Shimano Tourney" },
      { slot: "CASSETTE", value: "7/8-speed" },
      { slot: "BRAKES", value: "Mechanical disc" },
      { slot: "WHEEL_SIZE", value: '27.5" or 29"' },
      { slot: "TIRES", value: "Kenda MTB 2.1" },
      { slot: "BOTTOM_BRACKET", value: "Cartridge", standard: "BSA" },
    ],
  },

  // ─── Diamondback ─────────────────────────────────────────────────────────
  {
    brandName: "Diamondback",
    brandAliases: ["Diamondback Bicycles", "DB"],
    scraperKey: "diamondback",
    model: "Response",
    family: "Response",
    yearStart: 1990,
    yearEnd: 2005,
    category: "Mountain",
    subcategory: "Hardtail",
    sourceUrl: "https://www.diamondback.com/",
    confidence: 0.55,
    components: [
      { slot: "FRAME_MATERIAL", value: "Chromoly or aluminum" },
      { slot: "FORK", value: "Rigid or RockShox / Manitou" },
      { slot: "SHIFTERS", value: "Shimano Deore / LX" },
      { slot: "REAR_DERAILLEUR", value: "Shimano Deore" },
      { slot: "CASSETTE", value: "7/8-speed" },
      { slot: "CRANKSET", value: "Triple crankset" },
      { slot: "BOTTOM_BRACKET", value: "Square taper", standard: "BSA" },
      { slot: "BRAKES", value: "Cantilever or V-brake" },
      { slot: "WHEEL_SIZE", value: '26"' },
      { slot: "TIRES", value: "IRC / Panaracer 26x2.0" },
    ],
  },
  {
    brandName: "Diamondback",
    brandAliases: ["Diamondback Bicycles", "DB"],
    scraperKey: "diamondback",
    model: "Overdrive",
    family: "Overdrive",
    yearStart: 2006,
    yearEnd: 2026,
    category: "Mountain",
    subcategory: "Hardtail",
    sourceUrl: "https://www.diamondback.com/",
    confidence: 0.6,
    components: [
      { slot: "FRAME_MATERIAL", value: "Aluminum" },
      { slot: "FORK", value: "SR Suntour / RockShox, ~100mm" },
      { slot: "FRONT_TRAVEL", value: "100 mm" },
      { slot: "SHIFTERS", value: "Shimano Altus / Acera / Deore" },
      { slot: "REAR_DERAILLEUR", value: "Shimano Altus / Acera" },
      { slot: "CASSETTE", value: "8/9/10-speed" },
      { slot: "BRAKES", value: "Mechanical or hydraulic disc" },
      { slot: "WHEEL_SIZE", value: '27.5" or 29"' },
      { slot: "TIRES", value: "WTB / Kenda MTB" },
      { slot: "BOTTOM_BRACKET", value: "Cartridge", standard: "BSA" },
    ],
  },

  // ─── Kona ────────────────────────────────────────────────────────────────
  {
    brandName: "Kona",
    brandAliases: ["Kona Bikes", "Kona Bicycle Company"],
    scraperKey: "kona",
    model: "Cinder Cone",
    family: "Cinder Cone",
    yearStart: 1990,
    yearEnd: 2004,
    category: "Mountain",
    subcategory: "Hardtail",
    sourceUrl: "https://www.konaworld.com/",
    confidence: 0.55,
    components: [
      { slot: "FRAME_MATERIAL", value: "Chromoly or aluminum" },
      { slot: "FORK", value: "Rigid or RockShox / Manitou" },
      { slot: "SHIFTERS", value: "Shimano Deore / LX / XT" },
      { slot: "REAR_DERAILLEUR", value: "Shimano Deore / XT" },
      { slot: "CASSETTE", value: "7/8/9-speed" },
      { slot: "CRANKSET", value: "Race Face / Shimano triple" },
      { slot: "BOTTOM_BRACKET", value: "Square taper", standard: "BSA" },
      { slot: "BRAKES", value: "V-brake or early disc" },
      { slot: "WHEEL_SIZE", value: '26"' },
      { slot: "TIRES", value: "Maxxis / Panaracer 26x2.1" },
    ],
  },
  {
    brandName: "Kona",
    brandAliases: ["Kona Bikes", "Kona Bicycle Company"],
    scraperKey: "kona",
    model: "Process",
    family: "Process",
    yearStart: 2005,
    yearEnd: 2015,
    category: "Mountain",
    subcategory: "Trail",
    sourceUrl: "https://www.konaworld.com/",
    confidence: 0.6,
    components: [
      { slot: "FRAME_MATERIAL", value: "Aluminum or Scandium" },
      { slot: "FORK", value: "Fox / RockShox, ~120–140mm" },
      { slot: "REAR_SHOCK", value: "Fox Float / RockShox Monarch", detail: "Full-suspension models" },
      { slot: "FRONT_TRAVEL", value: "120–140 mm" },
      { slot: "SHIFTERS", value: "Shimano Deore / SLX or SRAM X7" },
      { slot: "REAR_DERAILLEUR", value: "Shimano / SRAM 9/10-speed" },
      { slot: "CASSETTE", value: "9/10-speed" },
      { slot: "BRAKES", value: "Shimano / Avid hydraulic disc" },
      { slot: "WHEEL_SIZE", value: '26" or 27.5"' },
      { slot: "TIRES", value: "Maxxis High Roller / Minion" },
      { slot: "BOTTOM_BRACKET", value: "BSA or PF", standard: "Varies" },
    ],
  },
  {
    brandName: "Kona",
    brandAliases: ["Kona Bikes", "Kona Bicycle Company"],
    scraperKey: "kona",
    model: "Process 134",
    family: "Process",
    yearStart: 2016,
    yearEnd: 2026,
    category: "Mountain",
    subcategory: "Trail",
    sourceUrl: "https://www.konaworld.com/",
    confidence: 0.7,
    components: [
      { slot: "FRAME_MATERIAL", value: "6061 aluminum or carbon" },
      { slot: "FORK", value: "Fox 34 / RockShox Pike, ~140mm" },
      { slot: "REAR_SHOCK", value: "Fox Float DPS / RockShox Deluxe" },
      { slot: "FRONT_TRAVEL", value: "140 mm" },
      { slot: "REAR_TRAVEL", value: "134 mm" },
      { slot: "SHIFTERS", value: "Shimano Deore / SLX or SRAM NX/GX" },
      { slot: "REAR_DERAILLEUR", value: "Shimano / SRAM 12-speed" },
      { slot: "CASSETTE", value: "10-51t" },
      { slot: "CRANKSET", value: "1x, 30–32t" },
      { slot: "BOTTOM_BRACKET", value: "BSA threaded", standard: "BSA" },
      { slot: "BRAKES", value: "Shimano / SRAM 4-piston" },
      { slot: "WHEEL_SIZE", value: '29" or 27.5"' },
      { slot: "TIRES", value: "Maxxis Minion DHF / Dissector" },
      { slot: "AXLE", value: "Boost 148mm" },
    ],
  },

  // ─── Marin ───────────────────────────────────────────────────────────────
  {
    brandName: "Marin",
    brandAliases: ["Marin Bikes", "Marin Mountain Bikes"],
    scraperKey: "marin",
    model: "Muirwoods",
    family: "Muirwoods",
    yearStart: 1990,
    yearEnd: 2004,
    category: "Mountain",
    subcategory: "Hardtail",
    sourceUrl: "https://www.marinbikes.com/",
    confidence: 0.55,
    components: [
      { slot: "FRAME_MATERIAL", value: "Chromoly or Series 2 aluminum" },
      { slot: "FORK", value: "Rigid or RockShox / Manitou" },
      { slot: "SHIFTERS", value: "Shimano Deore / LX" },
      { slot: "REAR_DERAILLEUR", value: "Shimano Deore" },
      { slot: "CASSETTE", value: "7/8-speed" },
      { slot: "CRANKSET", value: "Triple crankset" },
      { slot: "BOTTOM_BRACKET", value: "Square taper", standard: "BSA" },
      { slot: "BRAKES", value: "Cantilever or V-brake" },
      { slot: "WHEEL_SIZE", value: '26"' },
      { slot: "TIRES", value: "IRC / Panaracer 26x2.0" },
    ],
  },
  {
    brandName: "Marin",
    brandAliases: ["Marin Bikes", "Marin Mountain Bikes"],
    scraperKey: "marin",
    model: "Bobcat Trail",
    family: "Bobcat",
    yearStart: 2005,
    yearEnd: 2026,
    category: "Mountain",
    subcategory: "Hardtail",
    sourceUrl: "https://www.marinbikes.com/",
    confidence: 0.65,
    components: [
      { slot: "FRAME_MATERIAL", value: "Series 2 / Series 3 aluminum" },
      { slot: "FORK", value: "SR Suntour / RockShox, ~100mm" },
      { slot: "FRONT_TRAVEL", value: "100 mm" },
      { slot: "SHIFTERS", value: "Shimano Altus / Acera / Deore" },
      { slot: "REAR_DERAILLEUR", value: "Shimano Altus / Deore" },
      { slot: "CASSETTE", value: "8/9/10/11-speed" },
      { slot: "BRAKES", value: "Shimano hydraulic or mechanical disc" },
      { slot: "WHEEL_SIZE", value: '27.5" or 29"' },
      { slot: "TIRES", value: "Vee Tire / WTB MTB" },
      { slot: "BOTTOM_BRACKET", value: "Cartridge", standard: "BSA" },
    ],
  },

  // ─── Gary Fisher ─────────────────────────────────────────────────────────
  {
    brandName: "Gary Fisher",
    brandAliases: ["Fisher", "Gary Fisher Bicycles", "Trek Gary Fisher"],
    scraperKey: "gary-fisher",
    model: "Hoo Koo E Koo",
    family: "Hoo Koo E Koo",
    yearStart: 1990,
    yearEnd: 1999,
    category: "Mountain",
    subcategory: "Hardtail",
    sourceUrl: null,
    confidence: 0.55,
    components: [
      { slot: "FRAME_MATERIAL", value: "Chromoly or aluminum" },
      { slot: "FORK", value: "Rigid or RockShox Judy / Mag 21" },
      { slot: "SHIFTERS", value: "Shimano Deore / LX / XT" },
      { slot: "REAR_DERAILLEUR", value: "Shimano Deore / XT" },
      { slot: "CASSETTE", value: "7/8-speed" },
      { slot: "CRANKSET", value: "Shimano / Race Face triple" },
      { slot: "BOTTOM_BRACKET", value: "Square taper", standard: "BSA" },
      { slot: "BRAKES", value: "Cantilever or V-brake" },
      { slot: "WHEEL_SIZE", value: '26"' },
      { slot: "TIRES", value: "Bontrager / IRC 26x2.0" },
    ],
  },
  {
    brandName: "Gary Fisher",
    brandAliases: ["Fisher", "Gary Fisher Bicycles", "Trek Gary Fisher"],
    scraperKey: "gary-fisher",
    model: "Tassajara",
    family: "Tassajara",
    yearStart: 2000,
    yearEnd: 2012,
    category: "Mountain",
    subcategory: "Hardtail",
    sourceUrl: null,
    confidence: 0.55,
    components: [
      { slot: "FRAME_MATERIAL", value: "Alpha aluminum" },
      { slot: "FORK", value: "RockShox / SR Suntour, ~80–100mm" },
      { slot: "FRONT_TRAVEL", value: "80–100 mm" },
      { slot: "SHIFTERS", value: "Shimano Deore / LX" },
      { slot: "REAR_DERAILLEUR", value: "Shimano Deore" },
      { slot: "CASSETTE", value: "8/9-speed" },
      { slot: "BRAKES", value: "V-brake or disc" },
      { slot: "WHEEL_SIZE", value: '26"' },
      { slot: "TIRES", value: "Bontrager 26x2.0–2.2" },
      { slot: "BOTTOM_BRACKET", value: "Cartridge", standard: "BSA" },
    ],
  },

  // ─── Haro ────────────────────────────────────────────────────────────────
  {
    brandName: "Haro",
    brandAliases: ["Haro Bikes", "Haro Bicycles"],
    scraperKey: "haro",
    model: "Escape",
    family: "Escape",
    yearStart: 1990,
    yearEnd: 2005,
    category: "Mountain",
    subcategory: "Hardtail",
    sourceUrl: "https://www.harobikes.com/",
    confidence: 0.5,
    components: [
      { slot: "FRAME_MATERIAL", value: "Hi-Ten or chromoly" },
      { slot: "FORK", value: "Rigid or RST" },
      { slot: "SHIFTERS", value: "Shimano Tourney / Altus" },
      { slot: "REAR_DERAILLEUR", value: "Shimano Tourney" },
      { slot: "CASSETTE", value: "7-speed freewheel" },
      { slot: "CRANKSET", value: "Triple crankset" },
      { slot: "BOTTOM_BRACKET", value: "Square taper", standard: "BSA" },
      { slot: "BRAKES", value: "V-brake" },
      { slot: "WHEEL_SIZE", value: '26"' },
      { slot: "TIRES", value: "Haro / Kenda 26x1.95" },
    ],
  },
  {
    brandName: "Haro",
    brandAliases: ["Haro Bikes", "Haro Bicycles"],
    scraperKey: "haro",
    model: "Flightline",
    family: "Flightline",
    yearStart: 2006,
    yearEnd: 2026,
    category: "Mountain",
    subcategory: "Hardtail",
    sourceUrl: "https://www.harobikes.com/",
    confidence: 0.6,
    components: [
      { slot: "FRAME_MATERIAL", value: "Aluminum" },
      { slot: "FORK", value: "SR Suntour, ~80–100mm" },
      { slot: "FRONT_TRAVEL", value: "80–100 mm" },
      { slot: "SHIFTERS", value: "Shimano Tourney / Altus" },
      { slot: "REAR_DERAILLEUR", value: "Shimano Tourney / Altus" },
      { slot: "CASSETTE", value: "7/8/9-speed" },
      { slot: "BRAKES", value: "Mechanical disc" },
      { slot: "WHEEL_SIZE", value: '27.5" or 29"' },
      { slot: "TIRES", value: "Kenda MTB 2.1" },
      { slot: "BOTTOM_BRACKET", value: "Cartridge", standard: "BSA" },
    ],
  },

  // ─── Motobécane ──────────────────────────────────────────────────────────
  {
    brandName: "Motobécane",
    brandAliases: ["Motobecane", "Motobécane USA"],
    scraperKey: "motobecane",
    model: "Mirage",
    family: "Mirage",
    yearStart: 1990,
    yearEnd: 1999,
    category: "Road",
    sourceUrl: null,
    confidence: 0.5,
    components: [
      { slot: "FRAME_MATERIAL", value: "Reynolds / Vitus steel or aluminum" },
      { slot: "FORK", value: "Steel road fork" },
      { slot: "SHIFTERS", value: "Simplex / Shimano friction or indexed" },
      { slot: "REAR_DERAILLEUR", value: "Simplex / Shimano" },
      { slot: "CASSETTE", value: "5/6/7-speed freewheel" },
      { slot: "CRANKSET", value: "Stronglight double" },
      { slot: "BOTTOM_BRACKET", value: "Square taper", standard: "French or BSA" },
      { slot: "BRAKES", value: "Mafac / Weinmann" },
      { slot: "WHEEL_SIZE", value: "700c" },
      { slot: "TIRES", value: "700x23–28" },
    ],
  },
  {
    brandName: "Motobécane",
    brandAliases: ["Motobecane", "Motobécane USA"],
    scraperKey: "motobecane",
    model: "Fantom",
    family: "Fantom",
    yearStart: 2000,
    yearEnd: 2026,
    category: "Mountain",
    subcategory: "Hardtail",
    sourceUrl: "https://www.motobecane.com/",
    confidence: 0.55,
    components: [
      { slot: "FRAME_MATERIAL", value: "Aluminum" },
      { slot: "FORK", value: "SR Suntour / RockShox, ~100mm" },
      { slot: "FRONT_TRAVEL", value: "100 mm" },
      { slot: "SHIFTERS", value: "Shimano Acera / Deore" },
      { slot: "REAR_DERAILLEUR", value: "Shimano Acera / Deore" },
      { slot: "CASSETTE", value: "8/9/10-speed" },
      { slot: "BRAKES", value: "Hydraulic or mechanical disc" },
      { slot: "WHEEL_SIZE", value: '27.5" or 29"' },
      { slot: "TIRES", value: "Kenda / Schwalbe MTB" },
      { slot: "BOTTOM_BRACKET", value: "Cartridge", standard: "BSA" },
    ],
  },

  // ─── Centurion ───────────────────────────────────────────────────────────
  {
    brandName: "Centurion",
    brandAliases: ["Centurion Bicycles"],
    scraperKey: "centurion",
    model: "LeMans",
    family: "LeMans",
    yearStart: 1990,
    yearEnd: 1999,
    category: "Road",
    sourceUrl: null,
    confidence: 0.5,
    components: [
      { slot: "FRAME_MATERIAL", value: "Tange / Ishiwata steel" },
      { slot: "FORK", value: "Steel road fork" },
      { slot: "SHIFTERS", value: "Shimano 105 / Sante / 600" },
      { slot: "REAR_DERAILLEUR", value: "Shimano 105 / 600" },
      { slot: "FRONT_DERAILLEUR", value: "Shimano 105 / 600" },
      { slot: "CASSETTE", value: "6/7/8-speed" },
      { slot: "CRANKSET", value: "Double crankset" },
      { slot: "BOTTOM_BRACKET", value: "Square taper", standard: "BSA 68mm" },
      { slot: "BRAKES", value: "Dual-pivot caliper" },
      { slot: "WHEEL_SIZE", value: "700c" },
      { slot: "TIRES", value: "700x23–25" },
    ],
  },
  {
    brandName: "Centurion",
    brandAliases: ["Centurion Bicycles"],
    scraperKey: "centurion",
    model: "Ironman",
    family: "Ironman",
    yearStart: 2000,
    yearEnd: 2015,
    category: "Road",
    sourceUrl: null,
    confidence: 0.5,
    components: [
      { slot: "FRAME_MATERIAL", value: "Aluminum road frame" },
      { slot: "FORK", value: "Carbon or alloy" },
      { slot: "SHIFTERS", value: "Shimano Sora / Tiagra / 105" },
      { slot: "REAR_DERAILLEUR", value: "Shimano Sora / Tiagra / 105" },
      { slot: "CASSETTE", value: "8/9/10-speed" },
      { slot: "BRAKES", value: "Caliper brakes" },
      { slot: "WHEEL_SIZE", value: "700c" },
      { slot: "TIRES", value: "700x23–28" },
      { slot: "BOTTOM_BRACKET", value: "Cartridge", standard: "BSA 68mm" },
    ],
  },

  // ─── Univega ─────────────────────────────────────────────────────────────
  {
    brandName: "Univega",
    brandAliases: ["Univega Bicycles"],
    scraperKey: "univega",
    model: "Alpina",
    family: "Alpina",
    yearStart: 1990,
    yearEnd: 2005,
    category: "Mountain",
    subcategory: "Hardtail",
    sourceUrl: null,
    confidence: 0.5,
    components: [
      { slot: "FRAME_MATERIAL", value: "Chromoly or aluminum" },
      { slot: "FORK", value: "Rigid or RST / RockShox" },
      { slot: "SHIFTERS", value: "Shimano Tourney / Altus / Deore" },
      { slot: "REAR_DERAILLEUR", value: "Shimano Tourney / Deore" },
      { slot: "CASSETTE", value: "7/8-speed" },
      { slot: "CRANKSET", value: "Triple crankset" },
      { slot: "BOTTOM_BRACKET", value: "Square taper", standard: "BSA" },
      { slot: "BRAKES", value: "Cantilever or V-brake" },
      { slot: "WHEEL_SIZE", value: '26"' },
      { slot: "TIRES", value: "IRC / Panaracer 26x1.95–2.1" },
    ],
  },
  {
    brandName: "Univega",
    brandAliases: ["Univega Bicycles"],
    scraperKey: "univega",
    model: "Via",
    family: "Via",
    yearStart: 2006,
    yearEnd: 2018,
    category: "Hybrid",
    sourceUrl: null,
    confidence: 0.5,
    components: [
      { slot: "FRAME_MATERIAL", value: "Aluminum" },
      { slot: "FORK", value: "Steel or SR Suntour comfort" },
      { slot: "SHIFTERS", value: "Shimano Tourney / Altus" },
      { slot: "REAR_DERAILLEUR", value: "Shimano Tourney" },
      { slot: "CASSETTE", value: "7/8-speed" },
      { slot: "BRAKES", value: "V-brake" },
      { slot: "WHEEL_SIZE", value: "700c" },
      { slot: "TIRES", value: "700x35–38c" },
      { slot: "BOTTOM_BRACKET", value: "Cartridge", standard: "BSA" },
    ],
  },

  // ─── Bridgestone ─────────────────────────────────────────────────────────
  {
    brandName: "Bridgestone",
    brandAliases: ["Bridgestone Cycle", "Bridgestone Bicycles", "Kabuki"],
    scraperKey: "bridgestone",
    model: "MB-Series",
    family: "MB",
    yearStart: 1990,
    yearEnd: 1994,
    category: "Mountain",
    subcategory: "Hardtail",
    sourceUrl: null,
    confidence: 0.55,
    components: [
      { slot: "FRAME_MATERIAL", value: "Chromoly (Tange Prestige / Ishiwata)" },
      { slot: "FORK", value: "Chromoly rigid or early suspension" },
      { slot: "SHIFTERS", value: "Shimano Deore XT / XTR" },
      { slot: "REAR_DERAILLEUR", value: "Shimano Deore XT / XTR" },
      { slot: "CASSETTE", value: "7-speed" },
      { slot: "CRANKSET", value: "Shimano XT triple" },
      { slot: "BOTTOM_BRACKET", value: "Square taper", standard: "BSA" },
      { slot: "BRAKES", value: "Shimano XT cantilever / V-brake" },
      { slot: "WHEEL_SIZE", value: '26"' },
      { slot: "TIRES", value: "IRC / Panaracer 26x2.0–2.1" },
    ],
  },
  {
    brandName: "Bridgestone",
    brandAliases: ["Bridgestone Cycle", "Bridgestone Bicycles", "Kabuki"],
    scraperKey: "bridgestone",
    model: "RB-Series",
    family: "RB",
    yearStart: 1990,
    yearEnd: 1994,
    category: "Road",
    sourceUrl: null,
    confidence: 0.55,
    components: [
      { slot: "FRAME_MATERIAL", value: "Chromoly or aluminum road" },
      { slot: "FORK", value: "Steel or aluminum road fork" },
      { slot: "SHIFTERS", value: "Shimano 105 / Ultegra / 600" },
      { slot: "REAR_DERAILLEUR", value: "Shimano 105 / Ultegra" },
      { slot: "FRONT_DERAILLEUR", value: "Shimano 105 / Ultegra" },
      { slot: "CASSETTE", value: "7/8-speed" },
      { slot: "CRANKSET", value: "Double crankset" },
      { slot: "BOTTOM_BRACKET", value: "Square taper", standard: "BSA 68mm" },
      { slot: "BRAKES", value: "Dual-pivot caliper" },
      { slot: "WHEEL_SIZE", value: "700c" },
      { slot: "TIRES", value: "700x23–25" },
    ],
  },
  {
    brandName: "Bridgestone",
    brandAliases: ["Bridgestone Cycle", "Bridgestone Bicycles", "Kabuki"],
    scraperKey: "bridgestone",
    model: "Anchor / Urban",
    family: "Urban",
    yearStart: 1995,
    yearEnd: 2026,
    category: "Hybrid",
    sourceUrl: null,
    confidence: 0.5,
    components: [
      { slot: "FRAME_MATERIAL", value: "Steel or aluminum" },
      { slot: "FORK", value: "Steel or alloy" },
      { slot: "SHIFTERS", value: "Shimano Tourney / Altus / Nexus hub" },
      { slot: "REAR_DERAILLEUR", value: "Shimano Tourney or internal hub", detail: "Varies by market" },
      { slot: "CASSETTE", value: "7-speed or internal gear hub" },
      { slot: "BRAKES", value: "V-brake or rim/roller" },
      { slot: "WHEEL_SIZE", value: "700c or 26\"" },
      { slot: "TIRES", value: "Urban / hybrid tread" },
      { slot: "BOTTOM_BRACKET", value: "Cartridge", standard: "BSA" },
    ],
  },

  // ─── Huffy ───────────────────────────────────────────────────────────────
  {
    brandName: "Huffy",
    brandAliases: ["Huffy Corporation", "Huffy Bicycles"],
    scraperKey: "huffy",
    model: "Mountain / Trail",
    family: "MTB",
    yearStart: 1990,
    yearEnd: 2009,
    category: "Mountain",
    subcategory: "Hardtail",
    sourceUrl: "https://www.huffy.com/",
    confidence: 0.5,
    components: [
      { slot: "FRAME_MATERIAL", value: "Hi-Ten steel" },
      { slot: "FORK", value: "Rigid or basic suspension" },
      { slot: "SHIFTERS", value: "Shimano Tourney / grip shift" },
      { slot: "REAR_DERAILLEUR", value: "Shimano Tourney" },
      { slot: "CASSETTE", value: "6/7-speed freewheel" },
      { slot: "CRANKSET", value: "Triple crankset" },
      { slot: "BOTTOM_BRACKET", value: "Square taper", standard: "BSA" },
      { slot: "BRAKES", value: "Linear-pull / V-brake" },
      { slot: "WHEEL_SIZE", value: '26"' },
      { slot: "TIRES", value: "Huffy / generic MTB 26x1.95–2.1" },
    ],
  },
  {
    brandName: "Huffy",
    brandAliases: ["Huffy Corporation", "Huffy Bicycles"],
    scraperKey: "huffy",
    model: "Rock Creek",
    family: "Rock Creek",
    yearStart: 2010,
    yearEnd: 2026,
    category: "Mountain",
    subcategory: "Hardtail",
    sourceUrl: "https://www.huffy.com/",
    confidence: 0.55,
    components: [
      { slot: "FRAME_MATERIAL", value: "Steel or aluminum" },
      { slot: "FORK", value: "SR Suntour / RST, ~50–80mm" },
      { slot: "FRONT_TRAVEL", value: "50–80 mm" },
      { slot: "SHIFTERS", value: "Shimano Tourney" },
      { slot: "REAR_DERAILLEUR", value: "Shimano Tourney" },
      { slot: "CASSETTE", value: "7-speed freewheel" },
      { slot: "BRAKES", value: "V-brake or mechanical disc" },
      { slot: "WHEEL_SIZE", value: '26" or 27.5"' },
      { slot: "TIRES", value: "Huffy MTB 2.0–2.1" },
      { slot: "BOTTOM_BRACKET", value: "Cartridge", standard: "BSA" },
    ],
  },
  {
    brandName: "Huffy",
    brandAliases: ["Huffy Corporation", "Huffy Bicycles"],
    scraperKey: "huffy",
    model: "Monolith",
    family: "Monolith",
    yearStart: 2015,
    yearEnd: 2026,
    category: "Mountain",
    subcategory: "Hardtail",
    sourceUrl: "https://www.huffy.com/",
    confidence: 0.6,
    components: [
      { slot: "FRAME_MATERIAL", value: "Aluminum hardtail" },
      { slot: "FORK", value: "SR Suntour XCT / similar, ~80–100mm" },
      { slot: "FRONT_TRAVEL", value: "80–100 mm" },
      { slot: "SHIFTERS", value: "Shimano Tourney / Altus" },
      { slot: "REAR_DERAILLEUR", value: "Shimano Tourney / Altus" },
      { slot: "CASSETTE", value: "7/8-speed" },
      { slot: "CRANKSET", value: "Triple or 1x entry crankset" },
      { slot: "BOTTOM_BRACKET", value: "Cartridge", standard: "BSA" },
      { slot: "BRAKES", value: "Mechanical disc" },
      { slot: "WHEEL_SIZE", value: '27.5" or 29"' },
      { slot: "TIRES", value: "Huffy / Kenda MTB 2.1–2.25" },
    ],
  },
];
